// Clarifying questions per procedure (Phase B).
// These gather non-sensitive operational context only; they assert no
// policy. Outcomes are produced by Phase C decision trees, which must
// be grounded in verified card content.

import type { DecisionQuestion } from "./types.ts";

export const QUESTION_SETS: Record<string, DecisionQuestion[]> = {
  pregnancy: [
    {
      id: "pregnancy_type",
      label: "Single or multiple pregnancy?",
      answerType: "single_choice",
      options: ["Single", "Multiple"],
      required: true,
      reason: "Verified pregnancy rules differ by pregnancy type.",
    },
    {
      id: "pregnancy_week",
      label: "Pregnancy week on the travel date?",
      answerType: "number",
      min: 1,
      max: 45,
      required: true,
      reason: "Eligibility windows are defined by week of pregnancy.",
    },
    {
      id: "certificate_available",
      label: "Is a medical certificate available?",
      answerType: "yes_no",
      required: false,
      reason: "Some weeks require a medical certificate.",
    },
  ],
  wheelchair: [
    {
      id: "assistance_level",
      label: "Which assistance level is required?",
      answerType: "single_choice",
      options: ["WCHR (ramp)", "WCHS (steps)", "WCHC (cabin seat)"],
      required: true,
      reason: "The SSR and handling requirements differ by level.",
    },
    {
      id: "battery_powered",
      label: "Is the wheelchair battery-powered?",
      answerType: "yes_no",
      required: true,
      reason: "Battery wheelchairs carry extra requirements.",
    },
    {
      id: "hours_before_departure",
      label: "How many hours remain before departure?",
      answerType: "number",
      min: 0,
      max: 1000,
      required: true,
      reason: "Notification windows depend on remaining time.",
    },
  ],
  "name-correction": [
    {
      id: "checked_in",
      label: "Is the passenger already checked in?",
      answerType: "yes_no",
      required: true,
      reason: "Check-in status changes who can action the correction.",
    },
    {
      id: "no_show",
      label: "Is the booking in no-show status?",
      answerType: "yes_no",
      required: true,
      reason: "No-show bookings follow a different path.",
    },
    {
      id: "correction_kind",
      label: "What kind of change is needed?",
      answerType: "single_choice",
      options: ["Character correction", "Title or spacing only", "Name swap", "Full name change"],
      required: true,
      reason: "Fees and permissions differ by correction type.",
    },
    {
      id: "booking_channel",
      label: "What is the booking channel?",
      answerType: "single_choice",
      options: ["Direct (FZ)", "GDS", "Interline", "Codeshare"],
      required: true,
      reason: "Channel restrictions apply to name changes.",
    },
  ],

  // ---------- Phase D: Sporting Equipment (GO TO v81.2 ch.28 pp.126-131) ----------
  "sporting-equipment": [
    {
      id: "speq_request",
      label: "Is this a new equipment booking or a cancellation/refund of an existing equipment fee?",
      answerType: "single_choice",
      options: ["New equipment booking", "Cancel or refund an existing equipment fee"],
      required: true,
      reason: "Refund eligibility follows a different verified rule than new bookings.",
      ruleAffected: "24-hour refundability rule (p.126 §12; p.129 notes 1-2)",
    },
    {
      id: "equipment_kind",
      label: "What type of equipment is being carried?",
      answerType: "single_choice",
      options: [
        "Standard sporting equipment",
        "Pole vault, javelin or hang glider",
        "Sporting weapon, firearm or ammunition",
      ],
      required: true,
      reason: "Weapons and restricted items have longer pre-booking and approval requirements.",
      ruleAffected: "24h standard / 48h restricted / 96h weapon pre-booking (pp.126-127)",
    },
    {
      id: "total_dimension_cm",
      label: "Total dimensions in cm (L + W + H) of the largest item?",
      answerType: "number",
      min: 1,
      max: 1000,
      required: true,
      reason: "SPEQ, SPEX, free carriage and pre-authorization bands are defined by total dimension.",
      ruleAffected: "Dimension bands: ≤159 free / 160-189 SPEQ / 190-350 SPEX / >350 pre-authorization (pp.126-127)",
    },
    {
      id: "equipment_count",
      label: "How many pieces of equipment are requested on this flight?",
      answerType: "number",
      min: 1,
      max: 50,
      required: true,
      reason: "SUP/FS may add up to 10 equipment per flight; beyond 10 needs Special Handling approval.",
      ruleAffected: "Maximum 10 equipment per flight (p.126 §2-3)",
    },
    {
      id: "hours_before_departure",
      label: "How many hours remain before departure?",
      answerType: "number",
      min: 0,
      max: 1000,
      required: true,
      reason: "Booking, pre-authorization and refund windows are all defined in hours before departure.",
      ruleAffected: "24h booking / 12h SUP-FS window / 48h pre-authorization / 96h weapons / 24h refund (pp.126-127)",
    },
    {
      id: "journey_type",
      label: "Is the journey point-to-point, connecting, or interline/codeshare?",
      answerType: "single_choice",
      options: ["Point-to-point", "FZ connecting", "Interline or codeshare"],
      required: true,
      reason: "Connecting and interline/codeshare requests are escalated to a Supervisor to add the SSR.",
      ruleAffected: "Connecting/interline/codeshare Supervisor handling (pp.128-130)",
    },
  ],

  // ---------- Phase D: Check-in / OLCI (GO TO v81.2 ch.55 pp.282-285) ----------
  "check-in-olci": [
    {
      id: "olci_goal",
      label: "What is the passenger trying to do?",
      answerType: "single_choice",
      options: [
        "Complete online check-in",
        "Modify or cancel after online check-in",
        "Add an SSR after check-in",
        "Online check-in error or issue",
      ],
      required: true,
      reason: "OLCI eligibility, offload and SSR requests follow separate verified rules.",
      ruleAffected: "OLCI window (p.283); offload handling (p.285)",
    },
    {
      id: "checkin_state",
      label: "What is the current check-in state?",
      answerType: "single_choice",
      options: ["Not checked in", "Checked in online", "Checked in at the airport"],
      required: true,
      reason: "Contact Centre must reject offload requests for passengers checked in at the airport.",
      ruleAffected: "Airport-checked-in restriction (p.285)",
    },
    {
      id: "minutes_to_departure",
      label: "How many minutes remain before departure?",
      answerType: "number",
      min: 0,
      max: 20000,
      required: true,
      reason: "OLCI runs 48 hours to 75 minutes before departure; offload is possible up to 60 minutes.",
      ruleAffected: "OLCI 2880-75 min window (p.283); 60-min offload deadline (p.285)",
    },
    {
      id: "card_verification",
      label: "Does the booking require debit/credit card verification at the airport?",
      answerType: "yes_no",
      required: true,
      reason: "Card-verification bookings are not eligible for online check-in.",
      ruleAffected: "OLCI non-eligible bookings (p.283 §5)",
    },
    {
      id: "has_exst_cbbg",
      label: "Does the booking include (or request) an Extra Seat or CBBG?",
      answerType: "yes_no",
      required: true,
      reason: "Extra-seat and cabin-baggage requests are not eligible for online check-in.",
      ruleAffected: "OLCI non-eligible bookings (p.283 §5)",
    },
  ],

  // ---------- Phase D: Flight Disruption (GO TO v81.2 ch.71 pp.329-340) ----------
  "flight-disruption": [
    {
      id: "fdis_popup",
      label: "Is a Flight Disruption pop-up available in the booking?",
      answerType: "single_choice",
      options: [
        "Disruption pop-up available",
        "'Flight not cancelled Changes' pop-up",
        "No pop-up",
      ],
      required: true,
      reason: "Agents must not offer anything free of charge without a pop-up or validated guidance.",
      ruleAffected: "First Call Resolution pop-up handling (p.331)",
    },
    {
      id: "booking_channel",
      label: "How was the booking issued?",
      answerType: "single_choice",
      options: [
        "Direct flydubai channel",
        "Travel shop",
        "TA portal",
        "GDS / interline / codeshare (TA or OAL system)",
      ],
      required: true,
      reason: "Self-service, refund and ticket-issuer responsibility differ by issuing channel.",
      ruleAffected: "Self-service scope (p.333); interline/codeshare handling (pp.338-340); TA refunds (p.335)",
    },
    {
      id: "request",
      label: "What is the passenger requesting?",
      answerType: "single_choice",
      options: ["Rebooking", "Refund or voucher"],
      required: true,
      reason: "Rebooking and refund follow different verified paths.",
      ruleAffected: "Rebooking window (pp.338-340); zonal refund logic (pp.334-335)",
    },
    {
      id: "olci_done",
      label: "Has online check-in been completed?",
      answerType: "yes_no",
      required: true,
      reason: "Self-service re-accommodation requires the flight status to be active (not online checked-in).",
      ruleAffected: "Accommodation self-servicing (p.333)",
    },
    {
      id: "hours_to_departure",
      label: "How many hours remain (or remained) to departure at the time of disruption handling?",
      answerType: "number",
      min: 0,
      max: 1000,
      required: true,
      reason: "For interline/codeshare TA/OAL bookings, Contact Centre honors rebooking only within 72 hours.",
      ruleAffected: "72-hour interline/codeshare rule (pp.338-340)",
    },
    {
      id: "refund_zone",
      label: "Which refund zone does SPRINT show for the booking?",
      answerType: "single_choice",
      options: ["Green", "Red or Amber", "Not shown / unknown"],
      required: true,
      reason: "Zonal logic decides refund to original form of payment versus voucher.",
      ruleAffected: "Zonal default form of refund (pp.334-335)",
    },
  ],

  // ---------- Phase D: Extra Seat / CBBG (GO TO v81.2 ch.33 pp.160-163) ----------
  "extra-seat-cbbg": [
    {
      id: "seat_request",
      label: "Is the request an Extra Seat (EXST) or a Cabin Baggage seat (CBBG)?",
      answerType: "single_choice",
      options: ["EXST (comfort)", "CBBG (cabin baggage seat)"],
      required: true,
      reason: "EXST and CBBG have different quantity, cabin and seating rules.",
      ruleAffected: "EXST vs CBBG terms (pp.160-161)",
    },
    {
      id: "cabin_class",
      label: "Which cabin is the passenger booked in?",
      answerType: "single_choice",
      options: ["Economy", "Business"],
      required: true,
      reason: "CBBG is not available for Business Class passengers.",
      ruleAffected: "Business Class CBBG restriction (p.160 §7)",
    },
    {
      id: "seat_count",
      label: "How many extra seats are requested?",
      answerType: "number",
      min: 1,
      max: 5,
      required: true,
      reason: "Maximum two EXST per passenger; only one CBBG per passenger.",
      ruleAffected: "Quantity limits (p.161 §16)",
    },
    {
      id: "item_weight_kg",
      label: "Item weight in kg (enter 0 for EXST comfort requests)?",
      answerType: "number",
      min: 0,
      max: 300,
      required: true,
      reason: "Baggage on the blocked seat must not exceed 75 kg.",
      ruleAffected: "75 kg blocked-seat limit (p.161 §18)",
    },
    {
      id: "can_secure",
      label:
        "Can the item be secured on the seat within the documented dimensions (max 55×45×40 cm at headrest height; musical instruments up to 140 cm)?",
      answerType: "yes_no",
      required: true,
      reason: "Items that cannot be properly secured with the seat belt may not be accepted.",
      ruleAffected: "Securing and dimension rules (p.161 §19-21)",
    },
    {
      id: "seat_rows",
      label: "Which rows are requested for the extra seat?",
      answerType: "single_choice",
      options: ["Standard rows", "Emergency exit / restricted rows (14-17)"],
      required: true,
      reason: "EXST must not be in emergency exit rows 15-16; CBBG must not be in rows 14-17.",
      ruleAffected: "Row restrictions (p.160 §9-10)",
    },
    {
      id: "checkin_status",
      label: "Is the passenger already checked in?",
      answerType: "single_choice",
      options: ["Not checked in", "Checked in"],
      required: true,
      reason: "Extra-seat requests are not OLCI-eligible and offload to add SSRs is not honored.",
      ruleAffected: "OLCI exclusions and offload SSR restriction (ch.55 pp.283, 285)",
    },
    {
      id: "hours_before_departure",
      label: "How many hours remain before departure?",
      answerType: "number",
      min: 0,
      max: 1000,
      required: true,
      reason: "Requests must be made at least 2 hours before departure; later requests are airport go-show only.",
      ruleAffected: "2-hour deadline and airport go-show handling (p.161 §23, §28)",
    },
    {
      id: "booking_channel",
      label: "What is the booking channel?",
      answerType: "single_choice",
      options: ["Direct / TA", "GDS", "Interline or codeshare"],
      required: true,
      reason: "EXST/CBBG cannot be an interline/codeshare document; GDS needs a separate PNR.",
      ruleAffected: "Channel restrictions (p.160 §1, §3)",
    },
    {
      id: "meda_case",
      label: "Is this a MEDA (medical) case?",
      answerType: "yes_no",
      required: true,
      reason: "Medical approval is required for MEDA cases.",
      ruleAffected: "MEDA approval (p.161 §22)",
    },
  ],

  // ---------- Phase D: Minimum Connection Time (GO TO v81.2 ch.25 pp.100-102) ----------
  "minimum-connection-time": [
    {
      id: "arrival_terminal",
      label: "Which terminal does the inbound flight arrive at?",
      answerType: "single_choice",
      options: ["T1", "T2", "T3"],
      required: true,
      reason: "MCT values are defined per terminal pairing.",
      ruleAffected: "MCT table (p.102)",
    },
    {
      id: "departure_terminal",
      label: "Which terminal does the onward flight depart from?",
      answerType: "single_choice",
      options: ["T1", "T2", "T3"],
      required: true,
      reason: "MCT values are defined per terminal pairing.",
      ruleAffected: "MCT table (p.102)",
    },
    {
      id: "carrier_pair",
      label: "What is the carrier pairing?",
      answerType: "single_choice",
      options: ["FZ-FZ", "FZ-OA", "FZ-SQ", "FZ-KE", "FZ-PR", "PR-FZ"],
      required: true,
      reason: "FZ-FZ, FZ-OA and the listed exception carriers (SQ, KE, PR) carry different MCT values.",
      ruleAffected: "MCT table and OA exceptions (p.102)",
    },
    {
      id: "connection_minutes",
      label: "What is the actual connection duration in minutes?",
      answerType: "number",
      min: 0,
      max: 4320,
      required: true,
      reason: "The duration is compared against the published minimum connection time.",
      ruleAffected: "MCT comparison (p.102)",
    },
  ],
};
