// Clarifying questions per procedure (Phase B).
// These gather non-sensitive operational context only; they assert no
// policy. Outcomes are produced by Phase C decision trees, which must
// be grounded in verified card content.

import type { DecisionQuestion } from "./types.ts";

export const QUESTION_SETS: Record<string, DecisionQuestion[]> = {
  pregnancy: [
    {
      id: "pregnancy_type",
      label: "Single or multiple pregnancy?",
      answerType: "single_choice",
      options: ["Single", "Multiple"],
      required: true,
      reason: "Verified pregnancy rules differ by pregnancy type.",
    },
    {
      id: "pregnancy_week",
      label: "Pregnancy week on the travel date?",
      answerType: "number",
      min: 1,
      max: 45,
      required: true,
      reason: "Eligibility windows are defined by week of pregnancy.",
    },
    {
      id: "certificate_available",
      label: "Is a medical certificate available?",
      answerType: "yes_no",
      required: false,
      reason: "Some weeks require a medical certificate.",
    },
  ],
  // Wheelchair and name-correction question sets are defined in the Phase H
  // section below (real deterministic trees replaced the Phase B placeholders).

  // ---------- Phase D: Sporting Equipment (GO TO v81.2 ch.28 pp.126-131) ----------
  "sporting-equipment": [
    {
      id: "speq_request",
      label: "Is this a new equipment booking or a cancellation/refund of an existing equipment fee?",
      answerType: "single_choice",
      options: ["New equipment booking", "Cancel or refund an existing equipment fee"],
      required: true,
      reason: "Refund eligibility follows a different verified rule than new bookings.",
      ruleAffected: "24-hour refundability rule (p.126 §12; p.129 notes 1-2)",
    },
    {
      id: "equipment_kind",
      label: "What type of equipment is being carried?",
      answerType: "single_choice",
      options: [
        "Standard sporting equipment",
        "Pole vault, javelin or hang glider",
        "Sporting weapon, firearm or ammunition",
      ],
      required: true,
      reason: "Weapons and restricted items have longer pre-booking and approval requirements.",
      ruleAffected: "24h standard / 48h restricted / 96h weapon pre-booking (pp.126-127)",
    },
    {
      id: "total_dimension_cm",
      label: "Total dimensions in cm (L + W + H) of the largest item?",
      answerType: "number",
      min: 1,
      max: 1000,
      required: true,
      reason: "SPEQ, SPEX, free carriage and pre-authorization bands are defined by total dimension.",
      ruleAffected: "Dimension bands: ≤159 free / 160-189 SPEQ / 190-350 SPEX / >350 pre-authorization (pp.126-127)",
    },
    {
      id: "equipment_count",
      label: "How many pieces of equipment are requested on this flight?",
      answerType: "number",
      min: 1,
      max: 50,
      required: true,
      reason: "SUP/FS may add up to 10 equipment per flight; beyond 10 needs Special Handling approval.",
      ruleAffected: "Maximum 10 equipment per flight (p.126 §2-3)",
    },
    {
      id: "hours_before_departure",
      label: "How many hours remain before departure?",
      answerType: "number",
      min: 0,
      max: 1000,
      required: true,
      reason: "Booking, pre-authorization and refund windows are all defined in hours before departure.",
      ruleAffected: "24h booking / 12h SUP-FS window / 48h pre-authorization / 96h weapons / 24h refund (pp.126-127)",
    },
    {
      id: "journey_type",
      label: "Is the journey point-to-point, connecting, or interline/codeshare?",
      answerType: "single_choice",
      options: ["Point-to-point", "FZ connecting", "Interline or codeshare"],
      required: true,
      reason: "Connecting and interline/codeshare requests are escalated to a Supervisor to add the SSR.",
      ruleAffected: "Connecting/interline/codeshare Supervisor handling (pp.128-130)",
    },
  ],

  // ---------- Phase D: Check-in / OLCI (GO TO v81.2 ch.55 pp.282-285) ----------
  "check-in-olci": [
    {
      id: "olci_goal",
      label: "What is the passenger trying to do?",
      answerType: "single_choice",
      options: [
        "Complete online check-in",
        "Modify or cancel after online check-in",
        "Add an SSR after check-in",
        "Online check-in error or issue",
      ],
      required: true,
      reason: "OLCI eligibility, offload and SSR requests follow separate verified rules.",
      ruleAffected: "OLCI window (p.283); offload handling (p.285)",
    },
    {
      id: "checkin_state",
      label: "What is the current check-in state?",
      answerType: "single_choice",
      options: ["Not checked in", "Checked in online", "Checked in at the airport"],
      required: true,
      reason: "Contact Centre must reject offload requests for passengers checked in at the airport.",
      ruleAffected: "Airport-checked-in restriction (p.285)",
    },
    {
      id: "minutes_to_departure",
      label: "How many minutes remain before departure?",
      answerType: "number",
      min: 0,
      max: 20000,
      required: true,
      reason: "OLCI runs 48 hours to 75 minutes before departure; offload is possible up to 60 minutes.",
      ruleAffected: "OLCI 2880-75 min window (p.283); 60-min offload deadline (p.285)",
    },
    {
      id: "card_verification",
      label: "Does the booking require debit/credit card verification at the airport?",
      answerType: "yes_no",
      required: true,
      reason: "Card-verification bookings are not eligible for online check-in.",
      ruleAffected: "OLCI non-eligible bookings (p.283 §5)",
    },
    {
      id: "has_exst_cbbg",
      label: "Does the booking include (or request) an Extra Seat or CBBG?",
      answerType: "yes_no",
      required: true,
      reason: "Extra-seat and cabin-baggage requests are not eligible for online check-in.",
      ruleAffected: "OLCI non-eligible bookings (p.283 §5)",
    },
  ],

  // ---------- Phase D: Flight Disruption (GO TO v81.2 ch.71 pp.329-340) ----------
  "flight-disruption": [
    {
      id: "fdis_popup",
      label: "Is a Flight Disruption pop-up available in the booking?",
      answerType: "single_choice",
      options: [
        "Disruption pop-up available",
        "'Flight not cancelled Changes' pop-up",
        "No pop-up",
      ],
      required: true,
      reason: "Agents must not offer anything free of charge without a pop-up or validated guidance.",
      ruleAffected: "First Call Resolution pop-up handling (p.331)",
    },
    {
      id: "booking_channel",
      label: "How was the booking issued?",
      answerType: "single_choice",
      options: [
        "Direct flydubai channel",
        "Travel shop",
        "TA portal",
        "GDS / interline / codeshare (TA or OAL system)",
      ],
      required: true,
      reason: "Self-service, refund and ticket-issuer responsibility differ by issuing channel.",
      ruleAffected: "Self-service scope (p.333); interline/codeshare handling (pp.338-340); TA refunds (p.335)",
    },
    {
      id: "request",
      label: "What is the passenger requesting?",
      answerType: "single_choice",
      options: ["Rebooking", "Refund or voucher"],
      required: true,
      reason: "Rebooking and refund follow different verified paths.",
      ruleAffected: "Rebooking window (pp.338-340); zonal refund logic (pp.334-335)",
    },
    {
      id: "olci_done",
      label: "Has online check-in been completed?",
      answerType: "yes_no",
      required: true,
      reason: "Self-service re-accommodation requires the flight status to be active (not online checked-in).",
      ruleAffected: "Accommodation self-servicing (p.333)",
    },
    {
      id: "hours_to_departure",
      label: "How many hours remain (or remained) to departure at the time of disruption handling?",
      answerType: "number",
      min: 0,
      max: 1000,
      required: true,
      reason: "For interline/codeshare TA/OAL bookings, Contact Centre honors rebooking only within 72 hours.",
      ruleAffected: "72-hour interline/codeshare rule (pp.338-340)",
    },
    {
      id: "refund_zone",
      label: "Which refund zone does SPRINT show for the booking?",
      answerType: "single_choice",
      options: ["Green", "Red or Amber", "Not shown / unknown"],
      required: true,
      reason: "Zonal logic decides refund to original form of payment versus voucher.",
      ruleAffected: "Zonal default form of refund (pp.334-335)",
    },
  ],

  // ---------- Phase D: Extra Seat / CBBG (GO TO v81.2 ch.33 pp.160-163) ----------
  "extra-seat-cbbg": [
    {
      id: "seat_request",
      label: "Is the request an Extra Seat (EXST) or a Cabin Baggage seat (CBBG)?",
      answerType: "single_choice",
      options: ["EXST (comfort)", "CBBG (cabin baggage seat)"],
      required: true,
      reason: "EXST and CBBG have different quantity, cabin and seating rules.",
      ruleAffected: "EXST vs CBBG terms (pp.160-161)",
    },
    {
      id: "cabin_class",
      label: "Which cabin is the passenger booked in?",
      answerType: "single_choice",
      options: ["Economy", "Business"],
      required: true,
      reason: "CBBG is not available for Business Class passengers.",
      ruleAffected: "Business Class CBBG restriction (p.160 §7)",
    },
    {
      id: "seat_count",
      label: "How many extra seats are requested?",
      answerType: "number",
      min: 1,
      max: 5,
      required: true,
      reason: "Maximum two EXST per passenger; only one CBBG per passenger.",
      ruleAffected: "Quantity limits (p.161 §16)",
    },
    {
      id: "item_weight_kg",
      label: "Item weight in kg (enter 0 for EXST comfort requests)?",
      answerType: "number",
      min: 0,
      max: 300,
      required: true,
      reason: "Baggage on the blocked seat must not exceed 75 kg.",
      ruleAffected: "75 kg blocked-seat limit (p.161 §18)",
    },
    {
      id: "can_secure",
      label:
        "Can the item be secured on the seat within the documented dimensions (max 55×45×40 cm at headrest height; musical instruments up to 140 cm)?",
      answerType: "yes_no",
      required: true,
      reason: "Items that cannot be properly secured with the seat belt may not be accepted.",
      ruleAffected: "Securing and dimension rules (p.161 §19-21)",
    },
    {
      id: "seat_rows",
      label: "Which rows are requested for the extra seat?",
      answerType: "single_choice",
      options: ["Standard rows", "Emergency exit / restricted rows (14-17)"],
      required: true,
      reason: "EXST must not be in emergency exit rows 15-16; CBBG must not be in rows 14-17.",
      ruleAffected: "Row restrictions (p.160 §9-10)",
    },
    {
      id: "checkin_status",
      label: "Is the passenger already checked in?",
      answerType: "single_choice",
      options: ["Not checked in", "Checked in"],
      required: true,
      reason: "Extra-seat requests are not OLCI-eligible and offload to add SSRs is not honored.",
      ruleAffected: "OLCI exclusions and offload SSR restriction (ch.55 pp.283, 285)",
    },
    {
      id: "hours_before_departure",
      label: "How many hours remain before departure?",
      answerType: "number",
      min: 0,
      max: 1000,
      required: true,
      reason: "Requests must be made at least 2 hours before departure; later requests are airport go-show only.",
      ruleAffected: "2-hour deadline and airport go-show handling (p.161 §23, §28)",
    },
    {
      id: "booking_channel",
      label: "What is the booking channel?",
      answerType: "single_choice",
      options: ["Direct / TA", "GDS", "Interline or codeshare"],
      required: true,
      reason: "EXST/CBBG cannot be an interline/codeshare document; GDS needs a separate PNR.",
      ruleAffected: "Channel restrictions (p.160 §1, §3)",
    },
    {
      id: "meda_case",
      label: "Is this a MEDA (medical) case?",
      answerType: "yes_no",
      required: true,
      reason: "Medical approval is required for MEDA cases.",
      ruleAffected: "MEDA approval (p.161 §22)",
    },
  ],

  // ---------- Phase D: Minimum Connection Time (GO TO v81.2 ch.25 pp.100-102) ----------
  "minimum-connection-time": [
    {
      id: "arrival_terminal",
      label: "Which terminal does the inbound flight arrive at?",
      answerType: "single_choice",
      options: ["T1", "T2", "T3"],
      required: true,
      reason: "MCT values are defined per terminal pairing.",
      ruleAffected: "MCT table (p.102)",
    },
    {
      id: "departure_terminal",
      label: "Which terminal does the onward flight depart from?",
      answerType: "single_choice",
      options: ["T1", "T2", "T3"],
      required: true,
      reason: "MCT values are defined per terminal pairing.",
      ruleAffected: "MCT table (p.102)",
    },
    {
      id: "carrier_pair",
      label: "What is the carrier pairing?",
      answerType: "single_choice",
      options: ["FZ-FZ", "FZ-OA", "FZ-SQ", "FZ-KE", "FZ-PR", "PR-FZ"],
      required: true,
      reason: "FZ-FZ, FZ-OA and the listed exception carriers (SQ, KE, PR) carry different MCT values.",
      ruleAffected: "MCT table and OA exceptions (p.102)",
    },
    {
      id: "connection_minutes",
      label: "What is the actual connection duration in minutes?",
      answerType: "number",
      min: 0,
      max: 4320,
      required: true,
      reason: "The duration is compared against the published minimum connection time.",
      ruleAffected: "MCT comparison (p.102)",
    },
  ],

  // ---------- Phase H: Wheelchair (GO TO v81.2 ch.34 pp.165-170) ----------
  wheelchair: [
    {
      id: "assistance_type",
      label: "Which wheelchair assistance level is required?",
      answerType: "single_choice",
      options: ["WCHR", "WCHS", "WCHC"],
      required: true,
      reason: "The SSR-add deadline and companion/certificate requirements differ by level.",
      ruleAffected: "Assistance level and timing (p.165)",
    },
    {
      id: "hours_before_departure",
      label: "How many hours remain before departure?",
      answerType: "number",
      min: 0,
      max: 1000,
      required: true,
      reason: "WCHR can be added up to 12h prior; WCHS/WCHC need 24h; battery wheelchairs need 48h notice.",
      ruleAffected: "Timing windows (pp.165, 167)",
    },
    {
      id: "battery_powered",
      label: "Is it a battery-powered wheelchair or mobility aid?",
      answerType: "yes_no",
      required: true,
      reason: "Battery wheelchairs require 48-hour notification and extra handling.",
      ruleAffected: "Battery notification and handling (pp.167-168)",
    },
    {
      id: "battery_type",
      label: "What battery type is it?",
      answerType: "single_choice",
      options: [
        "WCBD (dry-cell / gel)",
        "WCLB (lithium)",
        "WCBW (wet-cell)",
        "Not battery-powered",
      ],
      required: false,
      reason: "Lithium is carried in the cabin with Wh limits; wet/dry cells go in the hold.",
      ruleAffected: "Battery packaging conditions (pp.167-169)",
    },
    {
      id: "battery_damaged",
      label: "Does the battery show any sign of damage or leaking?",
      answerType: "yes_no",
      required: false,
      reason: "No battery can be accepted if there are any signs of damage or leaking.",
      ruleAffected: "Damaged battery restriction (pp.167-168)",
    },
    {
      id: "companion_available",
      label: "For WCHC: is a companion/helper travelling in the same cabin?",
      answerType: "yes_no",
      required: false,
      reason: "WCHC passengers must travel with a companion on an adjoining seat.",
      ruleAffected: "WCHC companion requirement (pp.165-166)",
    },
    {
      id: "medical_certificate_available",
      label: "For WCHC: is a fit-to-fly medical certificate available?",
      answerType: "yes_no",
      required: false,
      reason: "WCHC requires a fit-to-fly certificate signed by a licensed practitioner.",
      ruleAffected: "WCHC medical certificate (pp.165-166)",
    },
  ],

  // ---------- Phase H: Name Change / Correction (GO TO v81.2 ch.52 pp.276-279) ----------
  "name-correction": [
    {
      id: "correction_type",
      label: "What kind of name correction is needed?",
      answerType: "single_choice",
      options: [
        "Title, space, or up to 3 characters",
        "Name swap (no spelling change)",
        "More than 3 characters / full name / add or delete / maiden-to-married",
      ],
      required: true,
      reason: "Fees and documents differ by correction type.",
      ruleAffected: "Name correction charges (pp.276-277)",
    },
    {
      id: "hours_before_departure",
      label: "How many hours remain before departure?",
      answerType: "number",
      min: 0,
      max: 1000,
      required: true,
      reason: "Name correction is not permitted within 6 hours of departure.",
      ruleAffected: "6-hour restriction (p.276)",
    },
    {
      id: "no_show",
      label: "Was the passenger a no-show at any previous stage?",
      answerType: "yes_no",
      required: true,
      reason: "Name correction is not done after no-show or a utilized sector.",
      ruleAffected: "No-show / fully-active PNR (pp.276-277)",
    },
    {
      id: "checkin_state",
      label: "What is the check-in state?",
      answerType: "single_choice",
      options: ["Not checked in", "Online checked in", "Airport checked in"],
      required: true,
      reason: "Checked-in and OLCI passengers are handled at the airport, not offloaded.",
      ruleAffected: "Checked-in / OLCI handling (p.276)",
    },
    {
      id: "booking_channel",
      label: "What is the booking channel?",
      answerType: "single_choice",
      options: ["Direct (FZ)", "GDS", "Codeshare", "Interline", "TA block fare"],
      required: true,
      reason: "GDS/codeshare/TA-block are blocked; interline has an FZ-direct-channel exception.",
      ruleAffected: "Channel restrictions (pp.276, 278)",
    },
  ],

  // ---------- Phase H: Falcon Handling (GO TO v81.2 ch.27 pp.119-124) ----------
  "falcon-handling": [
    {
      id: "hours_before_departure",
      label: "How many hours remain before departure?",
      answerType: "number",
      min: 0,
      max: 2000,
      required: true,
      reason: "Falcon bookings must be submitted more than 48 hours before departure to obtain approval.",
      ruleAffected: "48-hour booking rule (pp.120, 124)",
    },
    {
      id: "falcon_count",
      label: "How many falcons are being carried on the flight?",
      answerType: "number",
      min: 1,
      max: 200,
      required: true,
      reason: "More than 15 falcons on a flight requires higher-authority (CCO) approval.",
      ruleAffected: "Over-15 CCO approval (p.121)",
    },
    {
      id: "cabin_class",
      label: "Which cabin is requested?",
      answerType: "single_choice",
      options: ["Economy", "Business"],
      required: true,
      reason: "Falcons cannot be carried on seats/perches in Business Class.",
      ruleAffected: "No Business Class carriage (p.122)",
    },
    {
      id: "destination_restriction",
      label: "Does the routing hit any restricted station?",
      answerType: "single_choice",
      options: [
        "None / standard",
        "DXB or DWC arrival",
        "DMM",
        "ULH or MED (Saudi)",
        "SPX, HBE or DBB (Egypt)",
      ],
      required: true,
      reason: "DMM is not allowed; Saudi and Egypt stations need extra authority approvals.",
      ruleAffected: "Destination restrictions (pp.122-123)",
    },
    {
      id: "journey_type",
      label: "Is the journey flydubai-only or interline/codeshare?",
      answerType: "single_choice",
      options: ["flydubai only (FZ)", "Interline or codeshare"],
      required: true,
      reason: "flydubai cannot accept falcons on behalf of other carriers.",
      ruleAffected: "Interline/codeshare restriction (p.123)",
    },
    {
      id: "approval_obtained",
      label: "Has the required airline approval already been obtained?",
      answerType: "yes_no",
      required: true,
      reason: "Prior airline approval is mandatory before carriage is confirmed.",
      ruleAffected: "Mandatory prior approval (pp.120, 124)",
    },
    {
      id: "required_details_available",
      label: "Are all the required falcon details available (flights, count, carriage manner, box dimensions, handler confirmation, contact)?",
      answerType: "yes_no",
      required: true,
      reason: "The falcon details table must be collected before escalating for approval.",
      ruleAffected: "Required details table (pp.120, 124)",
    },
  ],

  // ---------- Phase J-D Batch 1: Duplicate Booking (GO TO v81.2 ch.47 pp.268-270) ----------
  "duplicate-booking": [
    {
      id: "match_level",
      label: "How do the two bookings compare?",
      answerType: "single_choice",
      options: ["Identical in every detail", "Only one sector matches", "Not clearly a duplicate"],
      required: true,
      reason: "The bookings must match the documented duplicate criteria before the case is handled as a duplicate.",
      ruleAffected: "Duplicate-booking definition and exact/partial handling (pp.268-270)",
    },
    {
      id: "both_active",
      label: "Are both bookings fully active (no cancelled, no-show, or used segment)?",
      answerType: "yes_no",
      required: true,
      reason: "A no-show, used, or inactive segment requires exception review.",
      ruleAffected: "Inactive / no-show handling (p.269)",
    },
    {
      id: "fare_same",
      label: "Is the total fare the same on both bookings?",
      answerType: "yes_no",
      required: false,
      reason: "For an exact duplicate, same-fare and different-fare cases cancel a different booking.",
      ruleAffected: "Exact duplicate same/different fare (pp.269-270)",
    },
    {
      id: "other_channel",
      label: "Was either booking created through a travel agent or GDS?",
      answerType: "yes_no",
      required: false,
      reason: "Cross-channel duplicates require the issuing agent's involvement and approval.",
      ruleAffected: "Travel agency / GDS duplicate handling (p.269)",
    },
  ],

  // ---------- Phase J-D Batch 1: Government Deals (GO TO v81.2 ch.69 pp.322-324) ----------
  "government-deals": [
    {
      id: "request_type",
      label: "What is the request?",
      answerType: "single_choice",
      options: [
        "Create a new discounted booking",
        "Add an adult or child",
        "Add an infant",
        "Modify or cancel an existing deal booking",
      ],
      required: true,
      reason: "Contact Centre authority differs by request type; new deal bookings are travel-shop-only.",
      ruleAffected: "Government Deal creation / addition / modification (pp.322-324)",
    },
    {
      id: "interline_codeshare",
      label: "Is the itinerary interline or codeshare?",
      answerType: "yes_no",
      required: true,
      reason: "Government deals are not applicable to interline/codeshare bookings.",
      ruleAffected: "Government Deals exclusions (p.322)",
    },
  ],

  // ---------- Phase J-D Batch 1: Auto Split OD (GO TO v81.2 ch.11 Fare Types pp.49-50) ----------
  "auto-split-od": [
    {
      id: "fz_connection",
      label: "Is it an eligible FZ-FZ connection (not interline, codeshare or circular)?",
      answerType: "yes_no",
      required: true,
      reason: "Auto Split OD applies only to FZ-FZ connection bookings; other itineraries are excluded.",
      ruleAffected: "Auto Split OD exclusions (p.50)",
    },
    {
      id: "leg_pattern",
      label: "Which leg status pattern applies?",
      answerType: "single_choice",
      options: [
        "Leg 1 boarded, Leg 2 no-show",
        "Leg 1 no-show, Leg 2 boarded",
        "Other or both same status",
      ],
      required: true,
      reason: "An OD Split occurs only when the two legs have different statuses (boarded / no-show).",
      ruleAffected: "OD Split status trigger and restriction matrix (pp.49-50)",
    },
    {
      id: "request",
      label: "What does the customer want to do with the affected leg?",
      answerType: "single_choice",
      options: ["Modify the affected leg", "Cancel the affected leg"],
      required: false,
      reason: "Modification and cancellation of the no-show leg follow different rules.",
      ruleAffected: "Auto Split OD modification / cancellation matrix (pp.49-50)",
    },
  ],
};
