export const CHAPTER_CARD_MAP: Record<string, string[]> = {
  baggage: ["baggage-upgrade"],
  "name-change-correction": ["name-correction"],
  wheelchair: ["wheelchair"],
  "flight-disruption": ["flight-disruption"],
  "connection-and-transfers": ["minimum-connection-time"],
  "sporting-equipment": ["sporting-equipment"],
  "falcon-handling": ["falcon-handling"],
  "ways-to-check-in": ["lounge-access-during-olci"],
  "dubai-stopover": ["dubai-stopover"],
  seat: ["extra-seat-cbbg"],
  interline: ["interline-connection"],
  "government-deals": ["government-deals"],
  ssrs: ["wheelchair", "extra-seat-cbbg", "sporting-equipment", "falcon-handling"],
  "check-in": ["lounge-access-during-olci"],
  payment: ["baggage-upgrade"],
  visa: ["visa", "ok-to-board"],
  "ok-to-board": ["ok-to-board"],
  meal: ["meal"],
  pregnancy: ["pregnancy"],
  medical: ["meda"],
  gds: ["gds"],
  "auto-split-od": ["auto-split-od"],
  "fare-types": ["auto-split-od"],
};
